### ISSUE TITLE
yarn build produces code that does not compile

### ISSUE THREAD

**Issue by brianmhunt** [vlasenko/babel-jsx#1]
Note the line `  *async results(authManager) {}`, which is not valid javascript.

It should be `async * results(authManager) {}`

Here's the output:

```bash
$ yarn build
yarn run v1.7.0
$ babel index.js
import React from 'react';

const MyComp = {
  elementName: 'div',
  attributes: {},
  children: ['Hello']
};

async function* myfunc() {
  const array = [1, 2, 3];
  console.log(...array);
}

class SearchCriteria {
  *async results(authManager) {}
}

✨  Done in 0.49s.
```

**Comment by larixer** [comment]
@brianmhunt Yeah, this is really strange. Maybe some Babel bug? I'm still playing to overcome it...

**Comment by brianmhunt** [comment]
Thanks @vlasenko ... I suspect it's a babel bug, too.

**Comment by larixer** [comment]
@brianmhunt I have submitted bug report for `babel-plugin-syntax-async-generators`:
https://github.com/babel/babel/issues/8382

Let us see how it will go.

**Comment by larixer** [comment]
@brianmhunt Please check discussion at: https://github.com/babel/babel/issues/8382 This is a bug in Babel. It has been fixed for Babel 7, but there is no plans to backport the fix to Babel 6.

**Comment by brianmhunt** [comment]
Thanks @vlasenko — That's what I anticipated.

Oddly it looks to be a stupidly simple fix.

Thanks for digging into this.

**Comment by larixer** [comment]
@brianmhunt Yes, I'm going to submit PR in few mins, stay tuned

**Comment by larixer** [comment]
@brianmhunt Created PR that backports the fix from Babel 7 to Babel 6:
https://github.com/babel/babel/pull/8383

**Comment by brianmhunt** [comment]
Looks like this got merged in.  Thanks @vlasnko!

**Comment by brianmhunt** [comment]
Looks like this got merged in.  Thanks @vlasnko!

**Comment by larixer** [comment]
You are welcome @brianmhunt !
